version: '3.8'

services:
  spark-yarn-master:
    container_name: da-spark-yarn-master
    build:
      dockerfile: Dockerfile
      context: .
    image: da-spark-yarn-image
    entrypoint: ['./entrypoint.sh', 'master']
    volumes:
      - ./data:/opt/spark/datalake/raw
      - ../config:/opt/spark/config 
      - ../src:/opt/spark/src
    env_file:
      - .env.spark
    ports:
      - '9090:8080'
      - '9870:9870'
      - '7077:7077'
      - '8088:8088'


  spark-yarn-worker:
#    container_name: da-spark-worker
    image: da-spark-yarn-image
    entrypoint: ['./entrypoint.sh', 'worker']
    depends_on:
      - spark-yarn-master
    env_file:
      - .env.spark
    volumes:
      - ./data:/opt/spark/datalake/raw
      - ../config:/opt/spark/config 
      - ../src:/opt/spark/src

  yarn-history-server:
    container_name: da-spark-yarn-history
    image: da-spark-yarn-image
    entrypoint: ['./entrypoint.sh', 'history']
    depends_on:
      - spark-yarn-master
    env_file:
      - .env.spark
    ports:
      - '18080:18080'